kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-ui-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if $.Values.repoSecret.enabled }}
      imagePullSecrets:
      - name:  {{ $.Values.repoSecret.name }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-ui
          image: {{ required "A snapagogo.ui.image value is required" .Values.snapagogo.ui.image }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ .Values.snapagogo.ui.resources.cpu }}
              memory: {{ .Values.snapagogo.ui.resources.memory }}
          {{ if .Values.snapagogo.ui.resources.memorylimit }}
            limits:
              memory: {{ .Values.snapagogo.ui.resources.memory }}
          {{ end }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 10
      {{- if .Values.snapagogo.tolerations }}
      tolerations:
        {{- range $index, $element := .Values.snapagogo.tolerations }}
        - key: {{ $element.key }}
          operator: {{ $element.operator }}
          value: {{ $element.value }}
          effect: {{ $element.effect }}
        {{- end }}
      {{- end }}
{{- if .Values.repoSecret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.repoSecret.name }}
data:
  .dockerconfigjson:  {{ $.Values.repoSecret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end }}
