kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-db-service
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
  selector:
    app: {{ .Release.Name }}