## Default values for snapagogo

snapagogo:
  # image: [Docker repository for image]

  api:
    image: ontoserver.azurecr.io/snapagogo-api:latest
    resources:
      memory: 3Gi
      initialHeapSize: 2g
      maxHeapSize: 2g
      memorylimit: true
    hostNames:
      - api.snapagogo.app
    config:
      # This section is for server configuration via environment variables
      spring.security.oauth2.resourceserver.jwt.issuer-uri: https://auth.ontoserver.csiro.au/auth/realms/aehrc
      snap2snomed.security.authDomainUrl:                   https://auth.ontoserver.csiro.au/auth/realms/aehrc/protocol/openid-connect
      spring.datasource.driverClassName:                    software.aws.rds.jdbc.mysql.Driver
      spring.datasource.username:                           root
      snap2snomed.security.adminGroup:                      /snapagogoadmin

  ui:
    image: ontoserver.azurecr.io/snapagogo-api:latest
    hostNames:
      - www.snapagogo.app
      - snapagogo.app
    resources:
      memory: 256m
      memorylimit: false

  database:
    password: setonthecommandline

  tolerations: false
  highPriority: false

nginx-ingress:
  controller:
    enableSnippets: true
    enableCertManager: true
    ingressClassResource:
      name: snapagogo-nginx
      controllerValue: 'k8s.io/snapagogo-nginx'
      enabled: true
    service:
      annotations:
        service.beta.kubernetes.io/azure-dns-label-name: snapagogo
    ingressClass:
      create: true

ingress:
  tlsSecretName: snapagogo-tls-secret
  class: snapagogo-nginx
  nginx:
    sslRedirect: true

certmanager:
  enabled: true

repoSecret:
  enabled: false
  dockerconfigjson: # Docker config Json goes here if repo secret is enabled (e.g. for Quay IO images)