version: '3.2'
services:
  clair:
    container_name: snapagogo_api
    image: ontoserver.azurecr.io/snapagogo-api:latest
    environment:
      - snap2snomed.cors.allowedOriginPatterns=*
      - snap2snomed.cors.allowedHeaders=*
      - snap2snomed.cors.allowedMethods=OPTIONS,GET,POST,PUT,PATCH
      - snap2snomed.cors.maxAge=3600
      - snap2snomed.swagger.applicationVersion=0.1.0-SNAPSHOT
      - snap2snomed.swagger.applicationDescription=API Backend for the Snap2Snomed mapping tool
      - snap2snomed.swagger.applicationName=Snap2SNOMED API
      - snap2snomed.swagger.termsOfService=http://swagger.io/terms/
      - snap2snomed.swagger.licenseName=Apache 2.0
      - snap2snomed.swagger.licenseUrl=https://www.apache.org/licenses/LICENSE-2.0
      - snap2snomed.swagger.contactName=Australian e-Health Research Centre, CSIRO
      - snap2snomed.swagger.contactEmail=ontoserver-support@csiro.au
      - snap2snomed.swagger.contactUrl=https://aehrc.com/
      - snap2snomed.security.clientId=snapagogo
      - snap2snomed.security.audience=snapagogo
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.ontoserver.csiro.au/auth/realms/aehrc
      - snap2snomed.security.authDomainUrl=https://auth.ontoserver.csiro.au/auth/realms/aehrc/protocol/openid-connect
      - snap2snomed.defaultTerminologyServer.url=https://r4.ontoserver.csiro.au/fhir
      - spring.datasource.driverClassName=software.aws.rds.jdbc.mysql.Driver
      - spring.datasource.url=jdbc:mysql:aws://host.docker.internal/snapagogo
      - snap2snomed.security.adminGroup=snapagogoadmin
#      - logging.level.org.springframework=DEBUG
    ports:
      - "8080:8080"
